micronaut:
  server:
    port: 9999
    cors:
      enabled: true

  application:
    name: pong
  datasource:
    jdbc:
      type: HIKARI
  configurations:
    ui:
      allowed-origins:
        - http://localhost:8082
      allowed-headers:
        - Authorization
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pong
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

#eureka:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"